apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-app.fullname" . }}
  labels:
    app: {{ include "hello-app.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 3000 }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "hello-app.name" . }}
